[package]
name = "canonical-form"
version = "0.4.0"
authors = ["RÃ©mi de Verclos <r.deverclos@math.ru.nl>"]
readme = "README.md"
description = "Reduce graphs and other combinatorial structures modulo isomorphism."
license = "MIT"
repository = "https://github.com/avangogo/canonical-form"
documentation = "https://docs.rs/canonical-form"
keywords = ["graph", "group"]
publish = true
edition = "2018"

[dependencies]
